---
 - hosts: ubuntu
   become: true
   tasks:
    - name: update
      command: apt-get update -y

    - get_url:
       url: https://github.com/prometheus/prometheus/releases/download/0.15.1/prometheus-0.15.1.linux-amd64.tar.gz
       dest: /root/
       mode: 0777
       
    - name: create directory
      command: mkdir -p ~/prometheus/server
      
    - name: change directory
      command: chdir=prometheus/server ls 
      
    - unarchive:
       remote_src: yes
       src: prometheus-0.15.1.linux-amd64.tar.gz
       dest: /root/
       owner: root
       group: root
       mode: 0777
