
---
    - name: Add key for Mesosphere repository
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

    - name: Determine Linux distribution distributor
      shell:  DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
      register: release_distributor

    - name: Determine Linux distribution codename 
      shell: CODENAME=$(lsb_release -cs)
      register: release_codename

    - name: Add Mesosphere repository to sources list
      copy:
       content: "deb http://repos.mesosphere.io/{{release_distributor.stdout}} {{release_codename.stdout}} main"
       dest: /etc/apt/sources.list.d/mesosphere.list
       mode: 0777 
 
    - name: update
      command: apt-get update -y
 
    - name: adding repo for java 8
      command: add-apt-repository ppa:openjdk-r/ppa
      
    - name: install java 8
      apt: pkg=openjdk-8-jdk state=installed update_cache=true 
      
    - name: installpackages
      apt: name={{item}} state=latest 
      with_items:
       - mesosphere
       - mesos
       - zookeeper
 
    - name: setting zookeeper file for masters
      copy: 
       remote_src: yes
       src: /tmp/zk
       dest: /etc/mesos/zk
       owner: root
       group: root
       mode: 0777

    - name: Create zookeeper myid file
      template: 
       src: zoo_id.j2 
       dest: /etc/zookeeper/conf/myid
  
      notify:
       - Restart zookeeper
      when: zookeeper_action == "install"    
      
 # In template file add
 #{{ zoo.id }}
    
    - name: Zookeeper configuration file
      template:
       src: zoo.cfg
       dest: /etc/zookeeper/conf/zoo.cfg
       
      notify:
       - Restart zookeeper
      when: zookeeper_action == "install"
    
    - name: Modify the Quorum to Reflect your Cluster Size
      template:
       src: quorum
       dest: /etc/mesos-master/quorum
